name: Formula 1-2-3 update

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Update table'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: get directory structure
        run: tree
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/py/requirements.txt
      - name: execute py script # run py scripts to get the latest data
        run: |
          python ./scripts/py/F1 Data.py
          python ./scripts/py/F2 Data.py
          python ./scripts/py/F3 Data.py
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
